### ISSUE TITLE
Implement a "long" table option for LaTeX output

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#1367]
So that a very long tabular can split across pages (but not within a `sidebyside`).  We already use the `longtable` package for notation lists, and `list-of`.

Presumably a hint as an attribute on `table` and/or `tabular`.

Necessary for the homophone table in _Sound Writing_.

**Comment by rbeezer** [comment]
@sean-fitzpatrick reports success with swapping in the `longtable` environment for stock `tabular`.

* Need to check behavior inside of a `table` element, which may be under the control of `tcolorbox` and present challenges with `breakable` behavior.
* `longtable` provides some facilities for running items like "Continued..." and similar, see implementation for the table of notation.  This should be some sort of metadata type item for `tabular` or `table`.  Not attributes, as it is visible content.  Perhaps it could default to something like "Figure XX.YY continued"

**Comment by rbeezer** [comment]
From @sean-fitzpatrick on contemporaneous  `pretext-support` thread:

```
OK, I added more content.
Necessary changes to make a table work if it fills two pages:

- add \usepackage{longtable}
- add 'breakable' as an attribute to both tableptxstyle and tabularboxstyle
- replace tabular with longtable

With those changes, everything works just fine.

Maybe breakable tables could be a publisher option?
```

then

```
Correction: the tabularboxstyle doesn't need 'breakable' added to it.

```

**Comment by sean-fitzpatrick** [comment]
I'll do some experimenting when I get a chance. Last two days of vacation. I'll be on a plane during Friday drop-in so I'll have to miss this week.

Since this only affects LaTeX output, presumably you want an attribute on `tabular` rather than a new environment. Something like `<tabular long="yes">`, with `@long="no"` as the default?

Logic would have to be something like:

- if `@long="yes"`, write `\usepackage{longtable}`
- if `@long="yes", write new `ptxlongtablestyle` TCB setting. (Same as `ptxtablestyle`, with breakable added
- for a `table` containing a `tabular` with `@long="yes"`, use `ptxlongtablestyle` and replace `tabular` with `longtable`
- also do something for naked tabular (maybe then `tabularboxstyle` needs to be replaced by something breakable?)

The longtable package has a number of other features, such as the ability to add the "Continued on... Continued from" lines you mentioned above. Possibly some of these could be exposed by attributes as well?

**Comment by sean-fitzpatrick** [comment]
Did some testing: removing the `table` from the `tabular`, it's sufficient to add the longtable package, and change the tabular environment to longtable. (There is no tcolorbox involved.)

So the `pretext-latex.xsl` would have to:

1. determine if there are any `tabular` with `@long="yes"` (or whatever the attribute is)
2. if no, proceed as now
3. if yes, write a new tcolorbox style for long tables, add the longtable package, and:
    - for any table containing a `tabular/@long="yes"`, use the longtable tcb style
    - for any tabular with `@long="yes"` use the longtable environment instead of tabular

**Comment by rbeezer** [comment]
Thanks for all the sleuthing, @sean-fitzpatrick.  This is always the time-consuming part of a LaTeX change.

Would you prefer to write some XSL, or would you like me to?  Either way is fine.

Thinking about it more, you may wish a break on even a short table, maybe just while building a draft to fit on a certain number of pages.  Table might move later as part of page-fitting.  We already have a `@break` attribute for `md`, `mdn`, and `mrow` (search sample article).  Later it could become a global (publisher) setting if there is demand.

What do you think of `@break="yes|no"`?  Not so semantic, but this is a reaction to having page breaks.

**Comment by sean-fitzpatrick** [comment]
The existing `@break` attribute makes sense to me.

If you want this done soon, you should write the xsl.
If there's no hurry, I could do it.

August is a mix of a workshop, course prep (we begin right after Labour Day) and weeks with no childcare, so I don't anticipate having any spare time.

**Comment by rbeezer** [comment]
> you should write the xsl

OK, I'll see about tackling this until it gets rough.  Thanks for the off-list example, I'll see how that goes - but won't **commit** it.  ;-)

**Comment by rbeezer** [comment]
Announcement on `pretext-dev`

**Preliminary** implementation at aae0c183a617f26f62fb3d760bd70d959c6f1028 with two follow-on commits for documentation.

Improvements can be discussed on #1803
