### ISSUE TITLE
Braille Boxes Preceded by Blank Line

### ISSUE THREAD

**Issue by mcantino1** [PreTeXtBook/pretext#1861]
We currently don't have blank lines before boxed content. 

Boxes should be preceded by blank lines. 

From [BANA Formats](https://www.brailleauthority.org/formats/2016manual-web/section07.html):
7.2     Blank Lines
7.2.1Boxes are preceded and followed by blank lines.
a.  A top box line can appear on line 1 when a running head is not used and line 3 when a running head is used.
b.  A blank line separates a page change indicator from a box line.
Exceptions:
c.  Do not leave a blank line following a top box line.
d.  Do not leave a blank line preceding a bottom box line.
e.  Do not leave a blank line between boxed material and any accompanying heading, caption, directions, or source citation.
f.  Do not leave a blank line between adjacent interior and exterior box lines.
See Formats, §7.6.1 for use of blank lines for boxes within boxes.

**Comment by rbeezer** [comment]
Well, that took a while.  But I think we'll look back on this as a turning point.  A lot to reckon with.

Anyway, PreTeXt blocks should now have blanklines before and after, and box lines above and below, for embossing or for the electronic version.  Because we are doing it and not `liblouisutdml`.

We are still using `liblouisutdml` to keep initial conttent from splitting at the bottom of a page.

Blank lines do not collapse (end one box, start another).

We have traded several bad bugs for one sporadic bug.  If a box line is at the end of a page, then the page number forces it to be hyphenated.

Main changes at: 0096cfebf4003da4ffb152dea7fbd6f0aeff2603

Thanks, @mcantino1, for the careful report.
