### ISSUE TITLE
URLs in note in biblio don't appear

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#1990]
The "note" tag ordinarily seems to be a REMARK-LIKE object, *except* when it's inside a "biblio".  However, that means it still gets "caught" (I think) by things like &REMARK-FILTER and this causes an issue in a specific place, which is a url tag in the note of a biblio.  As a result, we get a \footnotemark{} in LaTeX and not a full footnote.   If I'm interpreting
https://github.com/PreTeXtBook/pretext/blob/master/xsl/pretext-latex.xsl#L10535
correctly.   In HTML we seem to get the footnote fine.

**Comment by kcrisman** [comment]
I think I can fairly easily exclude that particular case by amending the xsl:when at https://github.com/PreTeXtBook/pretext/blob/master/xsl/pretext-latex.xsl#LL10537C117-L10537C131 but would appreciate any comment on whether there is a preferred "slicker" or "PTX-style" way to do that before I go ahead and try something out.

**Comment by rbeezer** [comment]
Good catch.  Yes, we need to do fancy footwork to get footnotes out of tcolorbox (REMARK-LIKE), one of which is `note`.  Not clear to me why we are only getting **half** of what we need, though.  Give me a couple days to investigate before we agree on a course of action.

**Comment by kcrisman** [comment]
Thanks.  I'd appreciate any thoughts, because I need to fix this before releasing a new edition, and I should (hopefully?) be able to figure it out if you give a pointer for how not to create chaos 😄

**Comment by rbeezer** [comment]
It was a bit of a delicate fix, so I just went ahead and did it, since the absence of "the other half" of the footnote was a bit baffling at first.  One line of code and 8 or so lines of comments.;  ;-) 50dffb67a4b54987f6cc35d223ab0123969cf383

Two new footnotes in the sample article (as suggested on unrelated thread!) which will go live on the website in the next 24-48 hours.  6cc87da5633300854c3bdc9f25812cd37cec0633

Thanks!  That was a subtle one, and your diagnosis was spot-on.  Have I mentioned how much I despise footnotes?

**Comment by kcrisman** [comment]
>
> Thanks! That was a subtle one, and your diagnosis was spot-on. Have I
> mentioned how much I despise footnotes?
>
Thank YOU.  Not sure I could live without footnotes ...
