### ISSUE TITLE
Pretext repo is missing js/lib directory

### ISSUE THREAD

**Issue by ascholerChemeketa** [PreTeXtBook/pretext#2106]
@rbeezer Note for as you migrate PreTeXt to point at the css/js that has been moved into this repo.

There are two different repositories of js that PreTeXt depends on:
JS_Core (https://github.com/PreTeXtBook/JS_core) has been merged already
JS_lib (https://github.com/PreTeXtBook/JS_lib) needs to be merged still

I think there is some cleanup that could happen as part of that move. I can't find any evidence that `jquery.espy.js` or `jquery.sticky.js` are still in use in the codebase. Maybe @davidfarmer knows if they in use somewhere or are legacy code?

It also might be worth pointing at the official CDN for jquery 3.3.1 (https://code.jquery.com/jquery-3.3.1.min.js) instead of maintaining our own minified copy as `jquery.min.js`

**Comment by rbeezer** [comment]
I was about to pull this repository into PreTeXt.  But now I think it was skipped intentionally.

*  Does it serve a larger audience?  Is this the world-wide `knowl.js`, used, for example, by MathJax?
* A code comment suggests the JQuery being loaded are necessary only for the Table of Contents.
* I comment out the JQuery and to my eye the HTML behaves just fine.  I could put up a beta.

**Comment by rbeezer** [comment]
More evidence:

* July 2014 c1ba24d26bc599cb73700abf9a3599eb7db7e5bc Lots of "GSAP Animation Platform for granular animation control" and the first appearance of "sticky"
* August 2014 dc56ec434c3ee22b5f969737b47c4f4fa31d64c8 "espy" for smoother scrolling

**Comment by davidfarmer** [comment]
I see that JS_lib was not moved.  And I am not clear on what other than `knowl.js`,
and maybe `mathjaxknowl3.js` might still be needed.  Okay, maybe `jquery.min.js` also,
because I don't think I ever got around to rewriting the knowls code to not use jQuery.
(When knowls were created, jQuery was necessary, but today plain JavaScript is
much more functional.)

Probably it would be better to move those into the new-ish `js` directory of the
main repository?  I am available to discuss and/or do this during Friday drop-in.

**Comment by rbeezer** [comment]
Sounds good - thanks.  I think I will move it as-is, including history.

And I'll incorporate its pieces into an HTML build as local resources.

Then we can collectively move, remove, edit etc. without breaking anything.

Thanks for the reply.

**Comment by rbeezer** [comment]
In the repository now as `js_lib` and moved into builds as `js/lib`.

Eventually both instancs of `lib` should go away.
