### ISSUE TITLE
allow customizing whether new browser window/tab opens by default in links

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#281]
> > ```
> > But
> > 
> > <url href="..." open="internal|external" />
> > 
> > or similar would be entirely reasonable.  Copy that suggestion into an issue?
> > ```
> 
> I was actually hoping for this (though maybe not "internal" but "same"? unsure as to best wording) above the _blank but wasn't sure if you'd go for it.

**Comment by davidfarmer** [comment]
On the newsgroup I suggest this as a processing flag, not hard-coded
into the source:

What if we had the "open external links on a new page" (or not)
being a processing flag when the HTML is created?

The reason I have a problem with it being hard-coded, is that
anyone with a sufficient level of sophistication tends to want
all links to open in the current window: they "right click",
or whatever the appropriate terminology is on their system, to
open a new window if they want to do that.

Forcing everyone to get a new window every time is just imposing
beginner silliness on the rest of us.

And since it is a usability issue, it should not be something the author
has to think about.  But as a processing flag you can still
have whatever behavior you wish.  You can more easily share code between
documents if the links do not hard-code the behavior.

There may be additional issues when the screen is very small,
which is an additional argument for taking care of this in processing,
not in the MBX source.

**Comment by kcrisman** [comment]
>
> What if we had the "open external links on a new page" (or not)
> being a processing flag when the HTML is created?
>
>
I could imagine an author wanting certain things to open within same
window, and certain things not.  Maybe you think that is too micro-managing
for the author (and I do get the mobile device argument, that is
reasonable).


> The reason I have a problem with it being hard-coded, is that
> anyone with a sufficient level of sophistication tends to want
> all links to open in the current window: they "right click",
> or whatever the appropriate terminology is on their system, to
> open a new window if they want to do that.
>

I think a lot of my students expect new tabs, always and for everything.  I
mean everything.  So that is neither.


> And since it is a usability issue, it should not be something the author
> has to think about. But as a processing flag you can still
> have whatever behavior you wish. You can more easily share code between
> documents if the links do not hard-code the behavior.
>
>
True.

**Comment by davidfarmer** [comment]
Exactly: the so-called "young person who is technologically adept" is a 
myth.

While user expectation is a consideration, in terms of the wording of
one of the principles, this would be "common but unreasonable".

> I think a lot of my students expect new tabs, always and for everything. I
> mean everything. So that is neither.

**Comment by rbeezer** [comment]
Discussion at:

https://groups.google.com/d/topic/mathbook-xml-support/HE_07q_wS_s/discussion
