### ISSUE TITLE
what types of documents are there?

### ISSUE THREAD

**Issue by haraldschilly** [PreTeXtBook/pretext#324]
I'm new to mathbook xml, so excuse me my rather basic/stupid feature request.

When I look here: http://mathbook.pugetsound.edu/doc/author-guide/html/overview-structure.html I can see that there is an `<article>`, but I guess there is also a `<book>` type? Are there any other types, like report?

Expectation: This structure page should introduce each document type in a separate paragraph.

**Comment by rbeezer** [comment]
Dear Harald,

To answer your question there is `book` and `article`, which are the primary types supported.  There is `letter` and `memo`, which only convert to LaTeX (and maybe I am the only one using them).

The only real differences between `book` and `article` is that an `article` is partitioned as `section` or below, while a `book` must have a `chapter`.  Otherwise, front and back matter are more extensive for a `book`.

Documentation is nowhere near complete and grows in fits and spurts.  Your suggestion here is a good one, and I'll leave this open until I can expand/regorganize this part.

**Comment by haraldschilly** [comment]
ok, I see, I guessed it's all motivated from latex. 

and regarding `article`, I also assume that `abstract` is specific to it?

anyways, documentation is hard, I know :book:

**Comment by rbeezer** [comment]
**Partially** motivated by LaTeX. ;-)

You are right that an `abstract` will only be recognized as part of an article.  There is a DTD that describes much of this, but there are a few situations that it does not express properly (much like `abstract`).  Converse example: there are many front matter items that make sense for a `book` which do not make sense for an `article`.  Here's a [marginal UI into the DTD](http://mathbook.pugetsound.edu/doc/dtd/)
