### ISSUE TITLE
CSS for named lists, now captioned

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#704]
"Named lists" now look more like figures.  But content needs to be set off somehow, much like for "listing".  Using a frame (box) now.  But a Greg-L with NW hook might be good (just like on "pre" for listing?)  But whatever you think works is fine, of course.

div.named-list-content

Sandbox:  http://mathbook.pugetsound.edu/beta/20170829-namedlist/section-12.html

(In Section 12.6)

More on pretext-announce.

**Comment by davidfarmer** [comment]
I'll look after you take away the extra.css box

**Comment by rbeezer** [comment]
Just the bare file, no images, no extra CSS:

http://mathbook.pugetsound.edu/beta/20170829-namedlist-nocss/section-12.html

Thanks.

**Comment by davidfarmer** [comment]
The named list is in a "figure".  I guess that is okay, since it has a caption.

In the sample article, the figure has an h5.heading, containing an empty span.title

So two requests:

1. Remove the h5 and .title from that example, because those are empty.

2. If you expect examples of named lists with titles (which I assume you do,
which is why it is called "named"), then please add one to the
sample article so that I can style everything at once.  (If it goes in that same
section, please put a paragraph between them.)

**Comment by davidfarmer** [comment]
obsolete
