### ISSUE TITLE
meta tags in knowl files

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/pretext#785]
If you click the Example 4.2 knowl in the sample article (immediately following that
hidden example) you will see Greg's L inside the knowl.

The L should not be there.  The way I am deciding which article.example-like get the L
is by selecting on : not(: first-child).  The intention is that a knowl that only contains
a theorem or definition (or example) should not have the L.

Why do we get an L for Example 4.2?  Because the file containing the knowl content
has "meta" tags which appear in the knowl, before the article, so the article is
not the first child.

Not sure if those meta tags are necessary or can be handled another way.

Also not sure why the know file is a proper web page instead of bare content.

One option is for the knowls code to check if the knowl file contains a "body"
tag, and if it does, strip away everything but the content of the body.  Not
sure if this could mess up something like WW, which uses iframe.  Seems like
the knowls code should not have to do that.

**Comment by rbeezer** [comment]
On 12/13/2017 12:53 PM, David W. Farmer wrote:
> Why do we get an L for Example 4.2? Because the file containing the knowl content
> has "meta" tags which appear in the knowl, before the article, so the article is
> not the first child.
>
> Not sure if those meta tags are necessary or can be handled another way.

Running from memory.  The meta tag is there to contain a directive to robots (ie 
Google search) to not index the knowl file, since it is duplicate content.

Duplicate content has been a HUGE unanticipated chore.  But I think it is 100% 
under control in HTML conversion (not so in LaTeX).

Famous last words: it could be trivial to add a ".duplicate" to the article tag. 
  Could even be just a few lines.  I could look tomorrow, first thing.

Might that be a better way to go?  As in, more explicit?

**Comment by rbeezer** [comment]
Knowls are definitely fully-structured pages so as to have a place for

```html
<meta name="robots" content="noindex, nofollow">
```

I've also experiemented with the necessity of loading JS here for various interactive elements.  There may be other reasons.

`example-like` will happen three ways:

1.  Born visible, you want an L. ("visible")

2.  Born in a hidden knowl, I suspect you do not want the L here. ("embed")

3.  Duplicated in an xref knowl (subject of issue), you do not want an L here. ("xref")

Every PTX element in this list:
```xsl
&REMARK-LIKE;|&COMPUTATION-LIKE;|&DEFINITION-LIKE;|&ASIDE-LIKE;|poem|
&FIGURE-LIKE;|assemblage|blockquote|paragraphs|objectives|&EXAMPLE-LIKE;|
exercisegroup|exercise|&PROJECT-LIKE;|task|&SOLUTION-LIKE;|&THEOREM-LIKE;|
&AXIOM-LIKE;|proof|case|fn|contributor|biblio|biblio/note
```
"knows" which of the three scenarios above it is converting to, in advance of writing the HTML `article` element.  So we coul put any class names we/you like there.

Adding .visible (or similar) in case (1) could be used as an indicator for Greg's L.

Seems generally useful to push *all* this info (1-3) through to the CSS, since the CSS generally does not know "where the content is coming from."  And then excellent improvements (like different styling) can be made unambiguously.

Send questions or instructions. ;-)

**Comment by davidfarmer** [comment]
knowls are being redone in the overhaul, so this issue no longer helpful.
