### ISSUE TITLE
Need an id for the page

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/pretext#843]
Currently the HTML ids are section and subsection based.  I think we need an id that
covers the contents of each HTML page.

The reason is that as we have more interactivity, we need to save and remember
what the user has done in the past.  It is natural to do that on a per-HTML-page
basis. It adds a lot of overhead, and strikes me as fragile, to have the javascript
look for the outermost section on the page.

Something that might be easy, is to change the structure

main class="main"
  div id="#content" class="mathbook-content"

to

main class="main" id="globally_unique_id_for_that_page"
  div class="content mathbook-content"

Actually I am changing two things at once.  There is no current reason
to replace the content id with a content class, but it might be an easy CSS change,
and maybe it is better to use a class than an id?

The globally_unique_id_for_that_page could incorporate the id of the book
and the id of the top level chapter/section on that page.

It is fine to just add the id to main and worry later about the content id/class.

**Comment by rbeezer** [comment]
Concatenated the "internal-id" of the document root (book, article) with the "internal-id" of the root of the page (chapter, section, subsection).  Test version, with no images, no knowls:

http://mathbook.pugetsound.edu/beta/20180306-main-id/derivatives.html

These will be stable if the author provides an `xml:id` for each division that becomes a page, otherwise, they are computed automatically and editing can change numbering.

Not merged, so let me know if it is satisfactory.  `class` changes can be easy, but did not do that now.

**Comment by davidfarmer** [comment]
Not sure I like the word "section" in the id.  As in

   derivatives-section-fundamental-theorem
   derivatives-section-8

If there is a worry about not being unique, then can we
abbreviate to "sec" and "chap"?

One of the steps in declaring a "version" will be to put
an id on everything.  It is fine if paragraphs get an
auto-generated id, but authors will want to make a sensible
id for every chapter and section.

This seems fine for now, and I can start using it in testing.
It is fine if we tweak the ids later.

**Comment by rbeezer** [comment]
I had merged this (and pushed) by mistake, since I wasn't sure we were done with it.  I've reverted it, but can restore it if need be, perhaps with modifications.

**Comment by rbeezer** [comment]
I can't tell if recent work on `@permid` makes this moot, or not.  Do we need/want some HTML structural changes?
