### ISSUE TITLE
Font loading and selection in CSS

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#848]
We could move font loading/selection/choice out of generated HTML and into fluidly-updated CSS (which is perhaps where it belongs anyway).  But perhaps we need to do this when there is a clean break on a major update to CSS.  Thus preserving some notes here.

https://css-tricks.com/snippets/css/using-font-face/

See the `@import` section describing how Google Fonts can be selected within the CSS.  For current PTX we load Open Sans regular, bold (weight 600), italic, italic-bold via CSS that Google generates, and which is visible by following

https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic

Ditto (pretty much) for Inconsolata.

This would be a good first step toward enabling a wider variety of font choices as part of themes.

**Comment by Jahrme** [comment]
Another option, one that would help with load times, would be to use Google’s [Web Font Loader](https://github.com/typekit/webfontloader) to load the fonts via JavaScript. There is a [Stack Overflow post](https://stackoverflow.com/questions/43706597/google-web-font-loader-any-disadvantages) about the disadvantages and the only one listed is that because the fonts are loaded asynchronously the page may jump once the fonts are applied.

**Comment by davidfarmer** [comment]
I think you oversold the value of the Stack Overflow posting:
after a year it has no votes, no answers, and minimal comments.
And OP didn't quantify the page speed increase or method of
measuring it.

I am concerned about the interaction with MathJax, which needs font
information to do its work.

**Comment by Jahrme** [comment]
It was not my intention to imply that the post proved there were no drawbacks, simply that in response to the question there were none put forth.

As for MathJax, font sizing will likely be an issue in any setup minimizing render-blocking JavaScript and CSS as the trade off is less control over when assets are available in the render timeline in exchange for a quicker first meaningful paint.

However, it may be possible to lessen the render time issues by using MathJax’s (Match Web Fonts)[http://docs.mathjax.org/en/latest/options/other/MatchWebFonts.html] extension which is intended for pages utilizing web fonts and checks for font size changes so that it can adjust the MathJax font size.

I am not trying to imply that this course of action would be the best one, simply that it is a possibility.

**Comment by davidfarmer** [comment]
Fonts are part of the current major overhaul.
