### ISSUE TITLE
Allow border option on image elements

### ISSUE THREAD

**Issue by pseeburger** [PreTeXtBook/pretext#915]
I'd like the option to specify a border attribute on images.  Even if it's only to specify to show one or not.  Or we could allow various CSS options for the border including thickness, color, and whether it should be dashed or solid.

**Comment by davidfarmer** [comment]
Can you provide some examples (preferable HTML) for how this could be used?

**Comment by pseeburger** [comment]
It's just a time-saver for images that may look nicer with a border.  I ended up just using Preview to add the border on the image.

You can eliminate this issue, if others don't see a need for it.  I am just used to using CSS to adjust these things in my JavaScript webpages, so I am looking for similar options in this context.  I was adding images for the toolbar buttons in my Help manual in the flow of the text.  The images did not had their own borders hard-coded before, but I wanted them to look like the buttons I was describing.  I can just hard-code a border to get what I want here.

In some other circumstances I have also found it helpful to add a border around an image.

**Comment by davidfarmer** [comment]
I think this should be closed because:

- it is almost impossible to create PTX options that actually allow everything that anyone might want to do

- trying to do this just opens the door to repeating the mistakes of LaTeX

- a publisher who wanted to do this is capable of hacking the LaTeX and CSS to get what they specifically want.

**Comment by davidfarmer** [comment]
Closing for the reasons in my previous comment.
