### ISSUE TITLE
Footnote in titles

### ISSUE THREAD

**Issue by jirilebl** [PreTeXtBook/pretext#966]
A footnote[1] in a title ought to work, especially if it is the title of a theorem[2].  For example:

Theorem 1.2.3 (Beavis[3]-Butthead[4] Theorem[5]) I need TP for my bunghole.

Currently this does not work, at least in the HTML backend.

Since titles are generally rather short[6], it would be acceptable I think if a backend simply grouped all footnotes at the end of the title:

Theorem 1.2.3 (Beavis-Butthead Theorem[3][4][5]) I need TP for my bunghole.

It should not be in a title when used as a link from elsewhere, as in: "Blah blah.  This proposition would follow from the Beavis-Butthead Theorem.  Blah blah blah."  Footnotes need only be displayed in the presentation of the theorem.  If the theorem title in the presentation needs to be clickable, it could be solved by making only "Theorem 1.2.3" clickable.

--
[1] See Gibbon for proper usage.  See Hodgson for highly improper usage.
[2] Or any other kind of block type thing such as a lemma, exercise, etc.
[3] Charles K. Beavis was an English mathematician from Oxford.
[4] Butthead had nothing to do with the proof of this theorem, but it is standard naming.
[5] This is not really a theorem, perhaps a proposition.
[6] Let us not kid ourselves: http://www.guinnessworldrecords.com/world-records/358711-longest-title-of-a-book

**Comment by davidfarmer** [comment]
This suggestion:

 If the theorem title in the presentation needs to be clickable, it could be solved by making only "Theorem 1.2.3" clickable.

has accessibility problems, because someone using a screen reader does not see the title
associated to the link.

This thread from pretext-support

https://groups.google.com/forum/?hl=en#!topic/pretext-support/mlc6RhM1_Lg

has an extensive discussion of this idea.  If someone is seriously thinking about
working on the PreTeXt code to implement this, many headaches will be saved if the
proposed solution were discussed before any actual coding began.
